<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChiTietHopDongSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('chi_tiet_hop_dong')->insert([
            [
                'ma_hop_dong' => 1,
                'ma_van_phong' => 1,
                'dien_tich' => 100,
                'gia_thue' => 76000000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 2,
                'ma_van_phong' => 2,
                'dien_tich' => 104,
                'gia_thue' => 79040000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 3,
                'ma_van_phong' => 4,
                'dien_tich' => 330,
                'gia_thue' => 250800000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 4,
                'ma_van_phong' => 5,
                'dien_tich' => 202,
                'gia_thue' => 153520000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 5,
                'ma_van_phong' => 7,
                'dien_tich' => 264,
                'gia_thue' => 192720000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 6,
                'ma_van_phong' => 11,
                'dien_tich' => 384,
                'gia_thue' => 280320000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 7,
                'ma_van_phong' => 15,
                'dien_tich' => 184,
                'gia_thue' => 124200000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 8,
                'ma_van_phong' => 19,
                'dien_tich' => 200,
                'gia_thue' => 123000000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 9,
                'ma_van_phong' => 20,
                'dien_tich' => 216,
                'gia_thue' => 132840000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 125000,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 10,
                'ma_van_phong' => 21,
                'dien_tich' => 238,
                'gia_thue' => 150654000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 125000,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 11,
                'ma_van_phong' => 23,
                'dien_tich' => 190,
                'gia_thue' => 133000000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 12,
                'ma_van_phong' => 24,
                'dien_tich' => 77,
                'gia_thue' => 53900000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 13,
                'ma_van_phong' => 6,
                'dien_tich' => 144,
                'gia_thue' => 109440000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'ma_hop_dong' => 14,
                'ma_van_phong' => 13,
                'dien_tich' => 140,
                'gia_thue' => 94500000,
                'gia_dien' => 6000,
                'gia_nuoc' => 30000,
                'dich_vu_khac' => 137500,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);

    }
}