<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HoaDonSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('hoa_don')->insert([
            [
                'ma_hop_dong' => 1,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 76000000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 2,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 79040000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 3,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 250800000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 4,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 153520000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 5,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 12848000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 6,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 280320000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 7,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 124200000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 8,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 123000000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 9,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 132840000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 10,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 10043600,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 11,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 132999999,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
            [
                'ma_hop_dong' => 12,
                'thang_nam' => '2025-05',
                'so_dien' => null,
                'so_nuoc' => null,
                'tien_dien' => null,
                'tien_nuoc' => null,
                'tien_thue' => 53900000,
                'tong_tien' => null,
                'trang_thai' => 'chua thanh toan',
                'created_at' => '2025-06-29 22:43:12',
                'updated_at' => '2025-06-29 22:43:12',
            ],
        ]);
    }
}