<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HopDongSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('hop_dong')->insert([
            [
                'user_id' => 12,
                'ngay_bat_dau' => '2025-07-12',
                'ngay_ket_thuc' => now()->addMonths(6),
                'tong_tien_coc' => 228000000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 9,
                'ngay_bat_dau' => now()->subMonths(5),
                'ngay_ket_thuc' => now()->addMonths(12),
                'tong_tien_coc' => 237120000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 3,
                'ngay_bat_dau' => now()->subMonths(3),
                'ngay_ket_thuc' => now()->addMonths(9),
                'tong_tien_coc' => 752400000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 4,
                'ngay_bat_dau' => now()->subMonths(5),
                'ngay_ket_thuc' => now()->addMonths(3),
                'tong_tien_coc' => 460560000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 5,
                'ngay_bat_dau' => now()->subMonths(1),
                'ngay_ket_thuc' => now()->addMonths(11),
                'tong_tien_coc' => 578160000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 6,
                'ngay_bat_dau' => now()->subMonths(5),
                'ngay_ket_thuc' => now()->addMonths(9),
                'tong_tien_coc' => 840960000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 7,
                'ngay_bat_dau' => now()->subMonths(5),
                'ngay_ket_thuc' => now()->addMonths(8),
                'tong_tien_coc' => 372600000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 8,
                'ngay_bat_dau' => now()->subMonths(5),
                'ngay_ket_thuc' => now()->addMonths(5),
                'tong_tien_coc' => 369000000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 9,
                'ngay_bat_dau' => now()->subMonths(3),
                'ngay_ket_thuc' => now()->addMonths(7),
                'tong_tien_coc' => 398520000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 10,
                'ngay_bat_dau' => now()->subMonths(1),
                'ngay_ket_thuc' => now()->addMonths(12),
                'tong_tien_coc' => 451962000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 11,
                'ngay_bat_dau' => now()->subMonths(5),
                'ngay_ket_thuc' => now()->addMonths(5),
                'tong_tien_coc' => 399000000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 12,
                'ngay_bat_dau' => now()->subMonths(4),
                'ngay_ket_thuc' => now()->addMonths(7),
                'tong_tien_coc' => 161700000,
                'tinh_trang' => 'dang thue',
                'da_thanh_ly' => false,
                'ngay_thanh_ly' => null,
                'ghi_chu_thanh_ly' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 5,
                'ngay_bat_dau' => now()->subMonths(12),
                'ngay_ket_thuc' => '2025-02-12',
                'tong_tien_coc' => 328320000,
                'tinh_trang' => 'da thanh ly',
                'da_thanh_ly' => '1',
                'ngay_thanh_ly' => '2025-02-12',
                'ghi_chu_thanh_ly' => "Đã hoàn trả đủ cọc",
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'user_id' => 8,
                'ngay_bat_dau' => now()->subMonths(27),
                'ngay_ket_thuc' => now()->subMonths(7),
                'tong_tien_coc' => 283500000,
                'tinh_trang' => 'da thanh ly',
                'da_thanh_ly' => '1',
                'ngay_thanh_ly' => now()->subMonths(7),
                'ghi_chu_thanh_ly' => "Đã hoàn trả đủ cọc",
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

        ]);
    }
}