<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VanPhongSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('van_phong')->insert([
            [//1
                'ma_toa_nha' => 1,
                'ten_van_phong' => 'Van phong 1001',
                'slug' => 'van-phong-1001',
                'dien_tich' => 100,
                'gia_thue' => 760000,
                'mo_ta' => 'Van phong tang 3, view dep',
                'tien_ich' => 'May lanh, Wifi',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 1,
                'ten_van_phong' => 'Van phong 1002',
                'slug' => 'van-phong-1002',
                'dien_tich' => 104,
                'gia_thue' => 760000,
                'mo_ta' => 'Van phong tang 5, thoang mat',
                'tien_ich' => 'Thang may, Bao ve 24/7',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 1,
                'ten_van_phong' => 'Van phong 1003',
                'slug' => 'van-phong-1003',
                'dien_tich' => 176,
                'gia_thue' => 760000,
                'mo_ta' => 'Van phong tang 5, thoang mat',
                'tien_ich' => 'Thang may, Bao ve 24/7',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 2,
                'ten_van_phong' => 'Van phong 2001',
                'slug' => 'van-phong-2001',
                'dien_tich' => 330,
                'gia_thue' => 760000,
                'mo_ta' => 'Van phong nho, tien nghi',
                'tien_ich' => 'Wifi, Ban ghe',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [//5
                'ma_toa_nha' => 2,
                'ten_van_phong' => 'Van phong 2002',
                'slug' => 'van-phong-2002',
                'dien_tich' => 202,
                'gia_thue' => 760000,
                'mo_ta' => 'Van phong view bien',
                'tien_ich' => 'May lanh, Bao ve',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 2,
                'ten_van_phong' => 'Van phong 2003',
                'slug' => 'van-phong-2003',
                'dien_tich' => 144,
                'gia_thue' => 760000,
                'mo_ta' => 'Van phong nho, tien nghi',
                'tien_ich' => 'Wifi, Ban ghe',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 3,
                'ten_van_phong' => 'Van phong 3001',
                'slug' => 'van-phong-3001',
                'dien_tich' => 246,
                'gia_thue' => 730000,
                'mo_ta' => 'Van phong rong, sang trong',
                'tien_ich' => 'Thang may, Wifi, Bao ve',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 3,
                'ten_van_phong' => 'Van phong 3002',
                'slug' => 'van-phong-3002',
                'dien_tich' => 79,
                'gia_thue' => 730000,
                'mo_ta' => 'Tầng cao, view đẹp',
                'tien_ich' => 'Thang máy, Wifi, Bảo vệ',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 4,
                'ten_van_phong' => 'Van phong 4001',
                'slug' => 'van-phong-4001',
                'dien_tich' => 104,
                'gia_thue' => 675000,
                'mo_ta' => 'Có thể chia nhỏ không gian làm việc',
                'tien_ich' => 'Thang máy, Camera an ninh, Lễ tân',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [//10
                'ma_toa_nha' => 4,
                'ten_van_phong' => 'Van phong 4002',
                'slug' => 'van-phong-4002',
                'dien_tich' => 137,
                'gia_thue' => 675000,
                'mo_ta' => 'Thiết kế hiện đại, đầy đủ tiện nghi',
                'tien_ich' => 'Thang máy, Lễ tân, Máy phát điện',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 5,
                'ten_van_phong' => 'Van phong 5001',
                'slug' => 'van-phong-5001',
                'dien_tich' => 84,
                'gia_thue' => 730000,
                'mo_ta' => 'Thiết kế hiện đại, đầy đủ tiện nghi',
                'tien_ich' => 'Thang máy, Lễ tân, Máy phát điện',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 5,
                'ten_van_phong' => 'Van phong 5002',
                'slug' => 'van-phong-5002',
                'dien_tich' => 116,
                'gia_thue' => 730000,
                'mo_ta' => 'Văn phòng rộng, sang trọng',
                'tien_ich' => 'Máy lạnh, Thang máy, Khu vực tiếp khách',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 6,
                'ten_van_phong' => 'Van phong 6001',
                'slug' => 'van-phong-6001',
                'dien_tich' => 140,
                'gia_thue' => 675000,
                'mo_ta' => 'Có thể chia nhỏ không gian làm việc',
                'tien_ich' => 'Thang máy, Lễ tân, Máy phát điện',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 6,
                'ten_van_phong' => 'Van phong 6002',
                'slug' => 'van-phong-6002',
                'dien_tich' => 204,
                'gia_thue' => 675000,
                'mo_ta' => 'Văn phòng rộng, sang trọng',
                'tien_ich' => 'Thang máy, Wifi, Bảo vệ',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [//15
                'ma_toa_nha' => 6,
                'ten_van_phong' => 'Van phong 6003',
                'slug' => 'van-phong-6003',
                'dien_tich' => 184,
                'gia_thue' => 675000,
                'mo_ta' => 'Tầng cao, view đẹp',
                'tien_ich' => 'Thang máy, Wifi, Bảo vệ',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 7,
                'ten_van_phong' => 'Van phong 7001',
                'slug' => 'van-phong-7001',
                'dien_tich' => 946,
                'gia_thue' => 760000,
                'mo_ta' => 'Thiết kế hiện đại, đầy đủ tiện nghi',
                'tien_ich' => 'Máy lạnh, Wifi',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 8,
                'ten_van_phong' => 'Van phong 8001',
                'slug' => 'van-phong-8001',
                'dien_tich' => 435,
                'gia_thue' => 700000,
                'mo_ta' => 'Không gian yên tĩnh, thoáng mát',
                'tien_ich' => 'Máy lạnh, Wifi',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 8,
                'ten_van_phong' => 'Van phong 8002',
                'slug' => 'van-phong-8002',
                'dien_tich' => 470,
                'gia_thue' => 700000,
                'mo_ta' => 'Thiết kế hiện đại, đầy đủ tiện nghi',
                'tien_ich' => 'Máy lạnh, Thang máy, Khu vực tiếp khách',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 8,
                'ten_van_phong' => 'Van phong 8003',
                'slug' => 'van-phong-8003',
                'dien_tich' => 200,
                'gia_thue' => 615000,
                'mo_ta' => 'Tầng cao, view đẹp',
                'tien_ich' => 'Thang máy, Wifi, Bảo vệ',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [//20
                'ma_toa_nha' => 9,
                'ten_van_phong' => 'Van phong 9001',
                'slug' => 'van-phong-9001',
                'dien_tich' => 216,
                'gia_thue' => 615000,
                'mo_ta' => 'Gần thang máy, tiện di chuyển',
                'tien_ich' => 'Thang máy, Camera an ninh, Lễ tân',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'ma_toa_nha' => 9,
                'ten_van_phong' => 'Van phong 9002',
                'slug' => 'van-phong-9002',
                'dien_tich' => 238,
                'gia_thue' => 633000,
                'mo_ta' => 'Gần thang máy, tiện di chuyển',
                'tien_ich' => 'Thang máy, Camera an ninh, Lễ tân',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 10,
                'ten_van_phong' => 'Van phong 10001',
                'slug' => 'van-phong-10001',
                'dien_tich' => 80,
                'gia_thue' => 635000,
                'mo_ta' => 'Không gian yên tĩnh, thoáng mát',
                'tien_ich' => 'Thang máy, Camera an ninh, Lễ tân',
                'trang_thai' => 'dang trong',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 11,
                'ten_van_phong' => 'Van phong 11002',
                'slug' => 'van-phong-11002',
                'dien_tich' => 190,
                'gia_thue' => 700000,
                'mo_ta' => 'Văn phòng rộng, sang trọng',
                'tien_ich' => 'Thang máy, Camera an ninh, Lễ tân',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ma_toa_nha' => 11,
                'ten_van_phong' => 'Van phong 11002',
                'slug' => 'van-phong-11002',
                'dien_tich' => 77,
                'gia_thue' => 70000,
                'mo_ta' => 'Tầng cao, view đẹp',
                'tien_ich' => 'Máy lạnh, Wifi',
                'trang_thai' => 'da thue',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}